-- MySQL Script generated by MySQL Workbench
-- 03/25/17 22:36:45
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dotsdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dotsdb` ;

-- -----------------------------------------------------
-- Schema dotsdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dotsdb` DEFAULT CHARACTER SET latin1 ;
USE `dotsdb` ;

-- -----------------------------------------------------
-- Table `dotsdb`.`appUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dotsdb`.`appUser` ;

CREATE TABLE IF NOT EXISTS `dotsdb`.`appUser` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `dob` DATE NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `pw` VARCHAR(45) NOT NULL,
  `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dotsdb`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dotsdb`.`category` ;

CREATE TABLE IF NOT EXISTS `dotsdb`.`category` (
  `id` CHAR(5) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dotsdb`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dotsdb`.`product` ;

CREATE TABLE IF NOT EXISTS `dotsdb`.`product` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `category_id` CHAR(5) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(500) NULL DEFAULT NULL,
  `price` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `stock` INT(11) NOT NULL DEFAULT '0',
  `icon_url` VARCHAR(100) NULL DEFAULT NULL,
  `image_url` VARCHAR(100) NULL DEFAULT NULL,
  `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`, `category_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_product_category_idx` (`category_id` ASC),
  CONSTRAINT `fk_product_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `dotsdb`.`category` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dotsdb`.`basket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dotsdb`.`basket` ;

CREATE TABLE IF NOT EXISTS `dotsdb`.`basket` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `appUserId` INT NOT NULL,
  `status` CHAR(5) NOT NULL,
  `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dotsdb`.`basket_product_rel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dotsdb`.`basket_product_rel` ;

CREATE TABLE IF NOT EXISTS `dotsdb`.`basket_product_rel` (
  `basketId` INT NOT NULL,
  `productId` INT NOT NULL,
  `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`basketId`, `productId`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
