-- MySQL Script generated by MySQL Workbench
-- 03/25/17 23:35:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dotsdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dotsdb` ;

-- -----------------------------------------------------
-- Schema dotsdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dotsdb` DEFAULT CHARACTER SET latin1 ;
USE `dotsdb` ;

-- -----------------------------------------------------
-- Table `dotsdb`.`app_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dotsdb`.`app_user` ;

CREATE TABLE IF NOT EXISTS `dotsdb`.`app_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `dob` DATE NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `pw` VARCHAR(45) NOT NULL,
  `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dotsdb`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dotsdb`.`category` ;

CREATE TABLE IF NOT EXISTS `dotsdb`.`category` (
  `id` CHAR(5) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dotsdb`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dotsdb`.`product` ;

CREATE TABLE IF NOT EXISTS `dotsdb`.`product` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `category_id` CHAR(5) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(500) NULL DEFAULT NULL,
  `price` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `stock` INT(11) NOT NULL DEFAULT '0',
  `icon_url` VARCHAR(100) NULL DEFAULT NULL,
  `image_url` VARCHAR(100) NULL DEFAULT NULL,
  `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`, `category_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_product_category_idx` (`category_id` ASC),
  CONSTRAINT `fk_product_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `dotsdb`.`category` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dotsdb`.`basket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dotsdb`.`basket` ;

CREATE TABLE IF NOT EXISTS `dotsdb`.`basket` (
  `id` INT(11) NOT NULL,
  `app_user_id` INT(11) NOT NULL,
  `status` CHAR(5) NOT NULL,
  `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `complete` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`, `app_user_id`),
  INDEX `fk_basket_app_user1_idx` (`app_user_id` ASC),
  CONSTRAINT `fk_basket_app_user1`
    FOREIGN KEY (`app_user_id`)
    REFERENCES `dotsdb`.`app_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dotsdb`.`basket_product_rel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dotsdb`.`basket_product_rel` ;

CREATE TABLE IF NOT EXISTS `dotsdb`.`basket_product_rel` (
  `product_id` INT(11) NOT NULL,
  `basket_id` INT(11) NOT NULL,
  `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`product_id`, `basket_id`),
  INDEX `fk_basket_product_rel_product1_idx` (`product_id` ASC),
  CONSTRAINT `fk_basket_product_rel_basket1`
    FOREIGN KEY (`basket_id`)
    REFERENCES `dotsdb`.`basket` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_basket_product_rel_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `dotsdb`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `dotsdb`.`app_user`
-- -----------------------------------------------------
START TRANSACTION;
USE `dotsdb`;
INSERT INTO `dotsdb`.`app_user` (`id`, `firstName`, `lastName`, `dob`, `email`, `pw`, `updated`, `created`) VALUES (DEFAULT, 'Dave', 'Sugrue', '1981-05-29', 'dave.sugrue@gmail.com', '888888', DEFAULT, DEFAULT);
INSERT INTO `dotsdb`.`app_user` (`id`, `firstName`, `lastName`, `dob`, `email`, `pw`, `updated`, `created`) VALUES (DEFAULT, 'Ian', 'Create', '1980-01-01', 'ian.create@gmail.com', '12345', DEFAULT, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `dotsdb`.`category`
-- -----------------------------------------------------
START TRANSACTION;
USE `dotsdb`;
INSERT INTO `dotsdb`.`category` (`id`, `name`, `updated`, `created`) VALUES ('TOOLS', 'Tools', DEFAULT, DEFAULT);
INSERT INTO `dotsdb`.`category` (`id`, `name`, `updated`, `created`) VALUES ('WAR', 'War', DEFAULT, DEFAULT);
INSERT INTO `dotsdb`.`category` (`id`, `name`, `updated`, `created`) VALUES ('ACTN', 'Action', DEFAULT, DEFAULT);
INSERT INTO `dotsdb`.`category` (`id`, `name`, `updated`, `created`) VALUES ('COMDY', 'Comedy', DEFAULT, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `dotsdb`.`product`
-- -----------------------------------------------------
START TRANSACTION;
USE `dotsdb`;
INSERT INTO `dotsdb`.`product` (`id`, `category_id`, `name`, `description`, `price`, `stock`, `icon_url`, `image_url`, `updated`, `created`) VALUES (DEFAULT, 'TOOLS', 'Hammer', 'A deluxe hammer for hitting nails...', 7.50, 50, NULL, NULL, DEFAULT, DEFAULT);
INSERT INTO `dotsdb`.`product` (`id`, `category_id`, `name`, `description`, `price`, `stock`, `icon_url`, `image_url`, `updated`, `created`) VALUES (DEFAULT, 'ACTN', 'Bad Boys', 'Bad boys, bad boys, watcha gonna do', 3, 25, NULL, NULL, DEFAULT, DEFAULT);
INSERT INTO `dotsdb`.`product` (`id`, `category_id`, `name`, `description`, `price`, `stock`, `icon_url`, `image_url`, `updated`, `created`) VALUES (DEFAULT, 'ACTN', 'Bad Boys II', 'Teh sequl to Bad Boys', 3.25, 7, NULL, NULL, DEFAULT, DEFAULT);

COMMIT;

